Шапка с фильтрами
Dante13Dark/react-app pull request #3
Opened 2022-10-25 21:13 UTC by Dante13Dark

Сделал шапку с фильтрами, 
по нажатию на кнопку сменить тему открывается дропдаун с выбором темы , 
при нажатии на фильтры появляется кнопка сбросить фильтры и открываются дополнительные фильтры,
при нажатии на фильтр по статусу открывает дропдаун и пишет выбранные значения в инпут

2022-10-29 14:35 UTC, Muslik requested changes
Ошибки разобрали на уроке

2022-10-30 14:01 UTC, Dante13Dark commented
Поправил замечания с урока, какие вспомнил

2022-10-31 14:30 UTC, Dante13Dark commented
Вспомнил еще, что говорили в кнопку текст не пропсом передавать, а как children. если не против то в следующем пр с таблицей поправлю

2022-11-01 00:55 UTC, Muslik requested changes
Будет видео

2022-11-01 06:00 UTC, Dante13Dark commented
Поправил замечания с видео от 1 ноября

2022-11-05 01:05 UTC, Muslik commented
<img width="466" alt="Screenshot 2022-11-05 at 04 05 02" src="https://user-images.githubusercontent.com/15676404/200094227-d06151a4-d885-4cf6-acfd-cba71f0b6f1c.png">
По прежнему вижу одинаковые id

2022-11-05 01:06 UTC, Muslik commented
<img width="330" alt="Screenshot 2022-11-05 at 04 06 08" src="https://user-images.githubusercontent.com/15676404/200094268-5655f5f2-2632-4a3a-890a-68c7a72f7b80.png">

2022-11-05 01:08 UTC, Muslik approved these changes
Просьба все таки исправить вещи на которые я кинул комментарии

2022-11-05 01:17 UTC, Muslik requested changes

2022-11-05 01:17 UTC, Muslik commented on src/components/shared/Button/Button.jsx
> +  primary: styles.primary,
Так. Я прошу прощения что я сразу этого не заметил!
Вы не должны экспортировать наружу классы.

2022-11-05 01:17 UTC, Muslik commented on src/components/shared/Button/Button.jsx
> +  primary: styles.primary,
Тут максимум может быть название тем

```javascript
export const BUTTON_THEME = {
  primary: 'primary',
}
```

А ниже вы уже применяете классы:

```javascript
<button className={cx(styles.button, {[styles.themePrimary]: theme === 'primary' })
```

2022-11-05 01:17 UTC, Muslik commented on src/components/shared/Button/Button.jsx
> +  primary: styles.primary,
В Input и других компонентах такая же логика должна быть

2022-11-05 01:17 UTC, Muslik commented on src/components/shared/Input/Input.jsx
> +          disabled={inputStyle === INPUT_STYLE.disabled}
disabled должно приходить не из стиля. А просто пропсом:

```javascript
<Input disabled />
```

2022-11-05 01:17 UTC, Muslik commented on src/components/shared/Input/Input.jsx
> +  default: styles.default,
Не нужен styles.default передавать. Он будет по умолчанию
Остается только один пропс - incorrect. Его можно передать напрямую. Без inputStyle

2022-11-05 06:39 UTC, Dante13Dark commented
поправил id у фильтра суммы и даты, 
стал передавать функцию напрямую в фильтре,
 в енаме стилей кнопки поправил значения на строки, 
убрал стили у инпута и перешел на incorrect и disabled

2022-11-06 21:44 UTC, Muslik approved these changes

2022-11-06 21:46 UTC, merged