Макет таблицы
Dante13Dark/react-app pull request #4
Opened 2022-11-01 06:09 UTC by Dante13Dark

Набросал макет таблицы, поправил цвета

2022-11-05 01:21 UTC, Muslik requested changes

2022-11-05 01:21 UTC, Muslik commented on src/components/pages/OrdersPage/modules/OrdersTable/OrdersTable.jsx
> +            {"Удалить"}
Зачем фигурные скобки

2022-11-05 01:21 UTC, Muslik commented on src/components/pages/OrdersPage/modules/OrdersTable/OrdersTable.jsx
> +            buttonStyle={cn(BUTTON_STYLE.primary, styles.button_danger)}
Появилась красная кнопка. У вас есть отличный вариант добавить ее как тему к вашей существующей кнопке.

2022-11-05 01:21 UTC, Muslik commented on src/components/pages/OrdersPage/modules/OrdersTable/OrdersTable.jsx
> +          <span className={styles.footer__text}>Выбрано записей: 5</span>
Цвет не как на макете

2022-11-05 01:21 UTC, Muslik commented on src/components/pages/OrdersPage/modules/OrdersTable/OrdersTable.jsx
> +      <TableBody>
Таблица должна быть на всю оставшуюся высоту

2022-11-05 01:21 UTC, Muslik commented on src/components/pages/OrdersPage/modules/OrdersTable/OrdersTable.jsx
> +          <TableHeaderCell className={styles.checkbox_cell}>
Тут должны быть стрелочки на полях которые будут сортироваться и должно быть активное состояние на поле по которому уже идет сортировка. Стрелочку может менять направление.

```javascript
<TableHeaderCell isActive={} direction={} />
```

2022-11-05 01:21 UTC, Muslik commented on src/components/pages/OrdersPage/modules/OrdersTable/OrdersTable.jsx
> +function getStatusText(status) {
Зачем стили хранить в объекте. Вы из этого можете сделать полноценный компонент и убрать отсюда:

```javascript
const Status = ({ name }) => {

}

<Status name="cancelled" />
```

2022-11-05 13:39 UTC, Dante13Dark commented
Убрал фигурные скобки у Button
Добавил стиль danger для Button
Растянул таблицу на всю высоту
Добавил стрелочки для ячеек с onClick
Вынес ячейку со статусом в отдельный компонент

2022-11-05 13:41 UTC, Dante13Dark commented
Не понимаю как сделать по нормальному ширину столбцов. Ширина столбцов в TableHeader и в TableBody без задания min-width отличается на несколько пикселей.

2022-11-06 21:47 UTC, Muslik commented
Есть проблемка ) У вас на страничке появился скролл

2022-11-06 21:47 UTC, Muslik commented
<img width="56" alt="Screenshot 2022-11-07 at 00 47 29" src="https://user-images.githubusercontent.com/15676404/200196962-44e9d5d9-abd5-4888-922b-e4622459d058.png">
Так. Что то с вашим чекбоксом

2022-11-06 21:48 UTC, Muslik commented
<img width="226" alt="Screenshot 2022-11-07 at 00 47 53" src="https://user-images.githubusercontent.com/15676404/200196978-af961d77-9f11-489f-ba59-bda727d62b28.png">

2022-11-06 21:48 UTC, Muslik commented
<img width="223" alt="Screenshot 2022-11-07 at 00 48 23" src="https://user-images.githubusercontent.com/15676404/200196996-f2c11843-ad4d-474d-b0f9-2600562144e5.png">
После того как выбрал статусы и кликнул на дропдаун и снова его открыл статусы там выбранные не остаются

2022-11-06 21:54 UTC, Muslik requested changes
Комменты оставил

2022-11-06 21:57 UTC, Muslik commented
> Не понимаю как сделать по нормальному ширину столбцов. Ширина столбцов в TableHeader и в TableBody без задания min-width отличается на несколько пикселей.

Там прикол скорее в скролле TableBody. Надо либо js-ом высчитывать ширину на которую делать padding у header-а либо вы нагуглите еще возможные варианты

2022-11-06 22:02 UTC, Dante13Dark commented
> Там прикол скорее в скролле TableBody. Надо либо js-ом высчитывать ширину на которую делать padding у header-а либо вы нагуглите еще возможные варианты

так там получается что tableBody что tableHeader контейнеры, внутри у которых одинаковый row лежит, внутри которого ячейки headerCell и просто cell с одинаковыми отсутпами и одинаковой шириной. Но в одном случае ячейка например 66,5 пикселей, в другом 66 пикселей. И соответственно все внутри body смещается относительно шапки.

2022-11-06 22:31 UTC, Muslik commented
> > Там прикол скорее в скролле TableBody. Надо либо js-ом высчитывать ширину на которую делать padding у header-а либо вы нагуглите еще возможные варианты
> 
> так там получается что tableBody что tableHeader контейнеры, внутри у которых одинаковый row лежит, внутри которого ячейки headerCell и просто cell с одинаковыми отсутпами и одинаковой шириной. Но в одном случае ячейка например 66,5 пикселей, в другом 66 пикселей. И соответственно все внутри body смещается относительно шапки.

> 

Именно потому что у body есть скролл а у header-а нет

2022-11-06 22:48 UTC, Muslik approved these changes

2022-11-06 22:48 UTC, merged