Redux
Dante13Dark/react-app pull request #5
Opened 2022-11-09 19:31 UTC by Dante13Dark

Фильтры, сортировка, пагинация.

2022-11-09 19:33 UTC, Dante13Dark commented
инпут пагинации завязал на нажатие Enter

2022-11-11 16:46 UTC, Muslik requested changes
Разобрали на уроке

2022-11-13 23:17 UTC, Dante13Dark commented
Не совсем понимаю чем помогает использование createSelector, у меня так же перерендеривается на каждое изменение стейта. (я непосредственно применяю пустые фильтры и сбрасываю пустые фильтры, диффа в стейте нет, но перерендер происходит). Возможно я неправильно использую. Но если я все 3 функции заворачиваю в createSelector, то он начинает не видеть изменения стейта в фильтрах, либо в сортировке.

2022-11-17 16:44 UTC, Muslik approved these changes

2022-11-17 16:44 UTC, Muslik commented
Будет видео

2022-11-17 17:03 UTC, merged